version: '3'
services:
  redis:
    image: "redis:alpine"
  maria_db:
    image: mariadb:10.3
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
    - "3306:3306"
  web:
    build: .
    ports:
      - "3000:${FLASK_RUN_PORT}"
    depends_on:
      - maria_db
    volumes: 
      - .:/app
    environment: 
      FLASK_ENV: ${FLASK_ENV}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
