version: '3'
services:
  maria_db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql_data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
  web:
    build: ./api
    restart: always
    env_file:
      - .env
    ports:
      - "80:${FLASK_RUN_PORT}"
      - "443:${FLASK_RUN_PORT}"
    depends_on:
      - maria_db
    volumes: 
      - ./api:/api
    environment: 
      FLASK_ENV: ${FLASK_ENV}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"